services:
  mongodb:
    image: mongo:7.0
    container_name: pole-chudes-mongodb-prod
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: pole-chudes-bot
      MONGO_INITDB_ROOT_AUTH_MECHANISM: scram-sha-256
    volumes:
      - mongodb_data_prod:/data/db
      - mongodb_config_prod:/data/configdb
    networks:
      - pole-chudes-network-prod
    command: ["--bind_ip_all", "--auth"]
    
  bot:
    build: .
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://${MONGO_ADMIN}:${MONGO_PASSWORD}@mongodb:27017/pole-chudes-bot?authSource=admin&authMechanism=SCRAM-SHA-256"
    networks:
      - pole-chudes-network-prod

volumes:
  mongodb_data_prod:
  mongodb_config_prod:

networks:
  pole-chudes-network-prod:
    driver: bridge